Mikud_Manage/Models/Message.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace Mikud_Manage.Models
{
    public class Message
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "ל-")]
        public string Reciever { get; set; }

        [Display(Name = "מ-")]
        public string Sender { get; set; }

        [Required]
        [Display(Name = "נושא")]
        public string Subject { get; set; }

        [Required]
        [Display(Name = "גוף ההודעה")]
        public string MessageBody { get; set; }

        public string IsRead { get; set; }

        [Display(Name = "תאריך שליחה")]
        public DateTime DateSend { get; set; }

    }
}

Mikud_Manage/Controllers/MessageController.cs
using System.Linq;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Mikud_Manage.Extensions;
using Mikud_Manage.Models;
using Mikud_Manage.Models.Repositories;

namespace Mikud_Manage.Controllers
{
    [Authorize]
    public class MessageController : BaseController
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private readonly IRepository<Message> _iRepository;
        private ApplicationDbContext db = new ApplicationDbContext();
        public MessageController()
        {
            _iRepository = new RepositoryMessages(new ApplicationDbContext());
        }

        public MessageController(IRepository<Message> repositoryMessageMock)
        {
            _iRepository = repositoryMessageMock;
        }

        // GET: /Message/
        public ActionResult Index()
        {
            string userIdentityGetUserName = User.Identity.GetUserName();
            var messages = _iRepository.Get(e => e.Reciever.Equals(userIdentityGetUserName)).ToList();
            return View(messages);
        }


        // GET: /Message/Create
        public ActionResult Create()
        {
            ViewBag.AspNetUserId = new SelectList(db.Guards, "Id", "UserName");
            return View();
        }

        // POST: /Message/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Reciever,Subject,MessageBody")] Message message)
        {
            if (ModelState.IsValid)
            {
                message.Sender = User.Identity.GetUserName();
                message.DateSend = DateTimeExtension.DateTimeNow();
                _iRepository.Add(message);
                return RedirectToAction("Index");
            }
            return View(message);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int messageId)
        {
            _iRepository.Delete(messageId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Respond(int messageId)
        {
            var message = _iRepository.Get(messageId);
            return View(message);
        }

    }
}

Mikud_Manage/Views/Message/Create.cshtml
@model Message
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        @Html.Partial("_MailSubmenu")
        <div class="form-horizontal">
            <h4>Message</h4>
            <hr />
            @Html.ValidationSummary(true)

            <div class="form-group">
                @Html.LabelFor(model => model.Reciever, new {@class = "control-label col-md-2"})
                <div class="col-md-10">
                    @Html.DropDownList("AspNetUserId", String.Empty)
                    @Html.EditorFor(model => model.Reciever)
                    @Html.ValidationMessageFor(model => model.Reciever)
                </div>
            </div>
             
            <div class="form-group">
                @Html.LabelFor(model => model.Subject, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Subject)
                    @Html.ValidationMessageFor(model => model.Subject)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MessageBody, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MessageBody)
                    @Html.ValidationMessageFor(model => model.MessageBody)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Send" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>

Mikud_Manage/Views/Message/Index.cshtml
@model IEnumerable<Message>
@using Mikud_Manage.Extensions
@*@{
        Layout = null;
    }*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

</head>
<body>
    <div class="row" dir="RTL">
        <div class="col-sm-2" dir="RTL">
            @Html.AuthWarning(UserName)
        </div>
    </div>
    <div class="row" dir="RTL">
        <div class="col-sm-2" dir="RTL">
            @Html.Partial("_MailSubmenu")
        </div>
    </div>
    <div class="row" dir="RTL">
        <div class="col-sm-2" dir="RTL">
            @Html.ActionLink("Create New", "Create")
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3>Inbox</h3>
        </div>
        <div class="table-responsive">
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <th>
                            <span class="glyphicon glyphicon-ok">
                            </span>
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Reciever)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Subject)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.MessageBody)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.DateSend)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <th><input type="checkbox"></th>
                            <td>
                                @Html.DisplayFor(modelItem => item.Reciever)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Subject)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.MessageBody)
                            </td>
                            <td>
                                @using (Html.BeginForm("Respond", "Message", FormMethod.Get))
                                {
                                    @Html.Hidden("messageId", item.Id)
                                    @Html.AntiForgeryToken()
                                    <button class="btn btn-info" type="submit" value="Reply" onclick="javascript: Notify('הודעה נשלחה.', 'top-right', '5000', 'info', 'fa-envelope', true); return false;">Info</button>
                                    @*<input type="submit" value="Reply" />*@
                                }

                                @using (Html.BeginForm("Delete", "Message"))
                                {
                                    @Html.Hidden("messageId", item.Id)
                                    @Html.AntiForgeryToken()
                                    <input type="submit" value="Delete a message" />

                                }

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DateSend)
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
    @section PageScripts {
        @Styles.Render("~/css/bootstrap-rtl")
        @Styles.Render("~/css/beyond-rtl")
        @Styles.Render("~/css/site")
        @Scripts.Render("~/bundles/beyond")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/jquery-ui")
        @Scripts.Render("~/bundles/jqueryval")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/moment")
    }
</body>
</html>

Mikud_Manage/Views/Message/Respond.cshtml
@model Message

@*@{
    Layout = null;
}*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Respond</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm("Create","Message"))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Message</h4>
            <hr />
            @Html.ValidationSummary(true,"",new {@class = "text-danger"})

            @Html.HiddenFor(e => e.Reciever);
            @Html.HiddenFor(e=>e.Subject);
            <div class="form-group">
                @Html.LabelFor(model => model.MessageBody, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.MessageBody)
                    @Html.ValidationMessageFor(model => model.MessageBody)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Send" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</body>
</html>

Mikud_Manage/Views/Message/_MailSubmenu.cshtml
<h2>
    @Html.ActionLink("Message", "Index", "Message", null, new {@id = "MessageSubNav"})
</h2>